GET http://localhost:3003/auction

###

GET http://localhost:3003/auction/one/?title=Monalisa

###

POST http://localhost:3003/auction/post
Content-Type: application/json

{
    "id": 1,
    "title":"Serjão Berranteiro",
    "initial": 3000,
    "expiration": "2021-07-31"
}

###

POST  http://localhost:3003/auction/post
Content-Type: application/json

{
    "id": 2,
    "title": "Everyday",
    "initial": 4000,
    "expiration": "2021-08-25"
}

###

POST http://localhost:3003/auction/post
Content-Type: application/json

{
    "id": 3,
    "title": "Monalisa",
    "initial": 5000,
    "expiration": "2021-08-20"
}

###

POST http://localhost:3003/auction/post
Content-Type: application/json

{
    "id": 4,
    "title":"Enfim, a Hipocresia",
    "initial": 6000,
    "expiration":"2021-08-15"
}

###

POST http://localhost:3003/auction/post
Content-Type: application/json

{
    "id": 5,
    "title":"Don Quixote",
    "initial": 7000,
    "expiration":"2021-08-10"
}

###

POST http://localhost:3003/auction/post
Content-Type: application/json

{
    "id": 6,
    "title":"Ameno",
    "initial": 500000,
    "expiration":"2021-12-25" 
}

###

POST http://localhost:3003/auction/post
Content-Type: application/json

{
    "title":"Dorime",
    "initial": 7000000,
    "expiration":"2021-12-21" 
}


###
DELETE http://localhost:3003/auction/6

######### 

GET http://localhost:3003/bid/?id=11

###

POST http://localhost:3003/bid/post/
Content-Type: application/json

{
    "id": 12,
    "bid": 200000 ,
    "dates": "2021-08-02",
    "auction_id": 2
}

###

POST http://localhost:3003/bid/post/
Content-Type: application/json

{
    "id": 13,
    "bid": 300000 ,
    "dates": "2021-08-01",
    "auction_id": 3
}

###

DELETE http://localhost:3003/bid/12

###